FROM golang:1.14.9-alpine AS builder

RUN mkdir /build

ADD go.mod main.go /build/

WORKDIR /build

#Build com Flags de otimização de compilação
RUN go build -ldflags "-w" main.go

FROM scratch

COPY --from=builder /build/main /app/

WORKDIR /app

CMD ["./main"]